export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_ADD_ID = 'CART_ADD_ID';

export const CART_ITEMS_REQUEST = 'CART_ITEMS_REQUEST';

// export const CART_SAVE_REQUEST = 'CART_SAVE_REQUEST';
// export const CART_SAVE_SUCCESS = 'CART_SAVE_SUCCESS';
// export const CART_SAVE_FAIL = 'CART_SAVE_FAIL';

